### ISSUE TITLE
Discord plugin is not compiling with the latest version of AmxxCurl (Module name collision issue?)

### ISSUE THREAD

**Issue by ghost** [YaLTeR/hlkreedz#17]
The most known Curl Module is AmxxModule (https://github.com/Polarhigh/AmxxCurl) which I'm using to compile the Discord plugin, however, it fails to compile due to undefined methods.

Either the plugin is using a version that's way to old or it's using another Curl module that's named the same way.

**Comment by fireblizzard** [comment]
This is the cURL module in use: https://github.com/alldroll/curl_module/releases

The only thing I remember is that I tried the one you mentioned and couldn't get SSL to work.
Any help with that is appreciated, 'cos I've never worked with C++ so I don't know how set up a working environment for module development and much less how to debug modules.

**Comment by ghost** [comment]
AFAIK AmxxCurl does support SSL, because we could use it to call the Discord webhook directly without the need of a PHP relay script.

https://forums.alliedmods.net/showthread.php?p=2491393#post2491393

This post contains a working Discord Webhook AMXX script.

**Comment by fireblizzard** [comment]
Yeah, I mean, I checked that thread and wasted a good bunch of hours trying to get it to work 1 year ago. My only alternatives after that, were to debug what were going on (not feasible due to my ignorance about C++) or to use the cURL module currently in use. It was my best option at the time, and I can't tell you exactly what was going wrong, what errors or what happened, 'cos I can't remember right now.

Now, obviously, it's definitely better and simpler to communicate directly with Discord, and better yet if it's encrypted (although no sensitive data is being transferred, hence my passivity on the issue to date). It would be great to get it to work properly, but personally I'm quite afraid of wasting more time on something that currently works (even if it's a workaround and not a complete solution), and that I had a bad experience with.

The TODO list is still huge and I'm slowly completing those tasks, and also fixing exploits (within 1-3 days since discovery) when I feel like programming for the bhop/climb community, which is not as often as I'd like due to feeling uncomfortable with the variety of coding styles and hacks that can be found in the code (several people have already touched the plugin code; I did some refactoring in the unstable branch, but still needs more refactoring). With all of this I just mean that this issue is pretty far in my mental TODO list, not to say that it's not even listed in the TODO file of this repo nor in any TODO or FIXME in the code.

If you want to fiddle with that, I'm open to PRs, merging and testing.
This is how the WR notifier is formatting and showing the records in case you need to know:
![image](https://user-images.githubusercontent.com/16053926/58159946-c76bd580-7c7d-11e9-8598-aac6975b98f4.png)

**Comment by Th3-822** [comment]
https://pastebin.com/bhNZxqrL
This one has some small changes customizable on the .sma (also with cvars for the webhook name/image)...
Works **only** with Polarhigh's AmxxCurl
I didn't wanted to upload the whole module just for a PR, so i drop only the .sma

![Test Image (Old)](https://user-images.githubusercontent.com/1194200/61178944-87163d00-a5c6-11e9-8151-6784cec4927e.png)

**Comment by fireblizzard** [comment]
Thank you. I have successfully integrated your contribution. Gonna be testing it these days, I'll probably push it to unstable this evening.

Also I've made a few changes to your plugin:
- Added a cvar to show the tops in short format, so it fits the average smartphone screen in portrait orientation. That's basically why the format that was in place doesn't look nice in wide screens and has the date removed, because it was made to look good in smartphones (people complained about the wide format). With the cvar you can now choose whether to keep the short format (default) or use yours.
- Added few cvars to customize stuff like the minimum entries to trigger the webhook, how many records to show each time (if that many records exist) and which tops types do you want notifications for.
- Somewhat fixed the case when 2 WRs have to be processed at a time, usually Pure + Pro as Pure PB also triggers a Pro one if your Pro PB was worse, so both arrive nearly at the same time to the plugin and it wouldn't process the second one as it was still working on posting the first one. Just made that it attempts to process the second one once 0.3s later. Probably needs a better solution, but this works for now (tested).
- Adapted the top type handling to the latest unstable version, which I'll try merging into master this evening as it's quite stable now (in fact it's already merged in my local).
