### ISSUE TITLE
Is the header file wrong?  Cannot compile

### ISSUE THREAD

**Issue by a1193362693** [YaLTeR/hlkreedz#26]
AMX Mod X Compiler 1.8.3-dev+5201
Copyright (c) 1997-2006 ITB CompuPhase
Copyright (c) 2004-2013 AMX Mod X Team

C:\Users\Administrator\Desktop\scripting\include\hl_kreedz_util.inc(402) : warning 213: tag mismatch
C:\Users\Administrator\Desktop\scripting\include\hl_kreedz_util.inc(474) : warning 224: indeterminate array size in "sizeof" expression (symbol "")
C:\Users\Administrator\Desktop\scripting\include\hl_kreedz_util.inc(475) : warning 224: indeterminate array size in "sizeof" expression (symbol "")
C:\Users\Administrator\Desktop\scripting\include\hl_kreedz_util.inc(476) : warning 224: indeterminate array size in "sizeof" expression (symbol "")
Warning: Tag mismatch on line 949
Warning: Tag mismatch on line 950
Warning: Tag mismatch on line 951
Warning: Tag mismatch on line 1698
Warning: Tag mismatch on line 1784
Warning: Tag mismatch on line 1820
Warning: Tag mismatch on line 1879
Warning: Tag mismatch on line 1905
Warning: Tag mismatch on line 2244
Error: Undefined symbol "MAX_MOTD_LENGTH" on line 2834
Error: Invalid expression, assumed zero on line 2834
Error: Undefined symbol "title" on line 2834
Error: Too many error messages on one line on line 2834

Compilation aborted.
4 Errors.
Could not locate output file C:\Users\Administrator\Desktop\hl_kreedz.amx (compile failed).

**Comment by fireblizzard** [comment]
Hey, I'm using AMXX 1.10 for the unstable branch, sorry for not specifying that anywhere.
`MAX_MOTD_LENGTH` is defined here:
https://github.com/alliedmodders/amxmodx/blob/master/plugins/include/amxconst.inc#L95

You can get it from here:
https://www.amxmodx.org/downloads-new.php?branch=master

I'm using the build 5390 at the moment. No plans to upgrade anytime soon.

**Comment by a1193362693** [comment]
Using plug-in server to crash repeatedly

**Comment by mxpph** [comment]
Try running it in debug mode by editing plugins.ini in the addons/amxmodx/configs folder with
`hl_kreedz.amxx debug`, and see if there is any error message in your server console.

**Comment by a1193362693** [comment]
The server starts and crashes

**Comment by a1193362693** [comment]
Shutdown plug-in server starts normally

**Comment by a1193362693** [comment]
//g_PauseSprite = precache_model("sprites/pause_icon.spr");

Server reboot due to missing files

**Comment by fireblizzard** [comment]
It's now in the _resources_ directory. I wanted to do this after reorganizing the directory structure, but that was planned for June since we're currently developing features for the upcoming Sourceruns cup and fixing any bug that affects the cup or the training process for it. That's the priority right now, but to be honest that sprite has been missing forever and it's a very simple addition, but since everyone has it downloaded from other HLKZ servers it's never been an issue with high priority. Sorry for any inconvenience.

I'm closing this as it's no longer about the original issue. If you have any other inconvenience, please open another one. Thanks.
